name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request info (needed if using comments/annotations on PRs)
  pull-requests: read

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
